import React, { forwardRef } from 'react';
import { useTranslation } from 'react-i18next';

// Standard Hex colors to avoid 'oklch' error in html2canvas
const styles = {
    container: { fontFamily: 'sans-serif', padding: '40px', backgroundColor: '#ffffff', color: '#111827', maxWidth: '800px', margin: '0 auto' },
    header: { textAlign: 'center', marginBottom: '30px', borderBottom: '2px solid #f3e8ff', paddingBottom: '20px' },
    title: { fontSize: '28px', fontWeight: 'bold', color: '#7e22ce', marginBottom: '8px', margin: 0 },
    subtitle: { color: '#6b7280', margin: 0, fontSize: '14px' },

    profileBox: { display: 'flex', justifyContent: 'space-between', marginBottom: '30px', backgroundColor: '#faf5ff', padding: '20px', borderRadius: '12px', border: '1px solid #f3e8ff' },
    profileCol: { textAlign: 'center', width: '50%' },
    profileName: { fontWeight: '600', color: '#581c87', fontSize: '18px', marginBottom: '4px', margin: 0 },
    label: { color: '#4b5563', fontSize: '14px', margin: 0 },

    scoreContainer: { textAlign: 'center', marginBottom: '30px' },
    scoreCircle: { display: 'inline-block', padding: '20px', borderRadius: '50px', backgroundColor: '#f3e8ff', marginBottom: '10px' },
    scoreTotal: { fontSize: '20px', color: '#a855f7' },

    sectionTitle: { fontSize: '18px', fontWeight: 'bold', color: '#1f2937', marginBottom: '15px', borderBottom: '1px solid #e5e7eb', paddingBottom: '8px' },

    table: { width: '100%', fontSize: '14px', borderCollapse: 'collapse', marginBottom: '30px' },
    th: { backgroundColor: '#f3e8ff', color: '#581c87', padding: '10px', textAlign: 'left', border: '1px solid #e9d5ff' },
    thCenter: { backgroundColor: '#f3e8ff', color: '#581c87', padding: '10px', textAlign: 'center', border: '1px solid #e9d5ff' },
    td: { padding: '10px', border: '1px solid #f3e8ff', color: '#374151' },
    tdPoints: { padding: '10px', border: '1px solid #f3e8ff', fontWeight: 'bold', color: '#7e22ce', textAlign: 'center' },
    rowAlt: { backgroundColor: '#faf5ff' },

    // Grid manually simulated with flex for safety
    analysisContainer: { display: 'flex', gap: '20px', marginBottom: '30px' },
    manglikBox: { flex: 1, backgroundColor: '#fef2f2', padding: '20px', borderRadius: '8px', border: '1px solid #fee2e2' },
    doshaBox: { flex: 1, backgroundColor: '#fff7ed', padding: '20px', borderRadius: '8px', border: '1px solid #ffedd5' },
    redTitle: { fontWeight: 'bold', color: '#991b1b', marginBottom: '8px', fontSize: '16px', margin: 0 },
    orangeTitle: { fontWeight: 'bold', color: '#9a3412', marginBottom: '8px', fontSize: '16px', margin: 0 },
    ptext: { fontSize: '14px', color: '#374151', margin: '4px 0' },

    aiBox: { backgroundColor: '#faf5ff', padding: '24px', borderRadius: '12px', border: '1px solid #f3e8ff', color: '#1f2937', lineHeight: '1.6', whiteSpace: 'pre-wrap', fontSize: '14px' },
    footer: { textAlign: 'center', fontSize: '12px', color: '#9ca3af', marginTop: '40px', paddingTop: '16px', borderTop: '1px solid #e5e7eb' }
};

const MatchReportPDF = forwardRef(({ matchResult, bride, groom }, ref) => {
    const { t } = useTranslation();

    if (!matchResult || !bride || !groom) return null;

    return (
        <div ref={ref} style={styles.container}>
            {/* Header */}
            <div style={styles.header}>
                <h1 style={styles.title}>
                    {t('kundaliMatch.reportTitle', 'Vedic Compatibility Report')}
                </h1>
                <p style={styles.subtitle}>
                    {t('common.generatedBy', 'Generated by AstroPinch')}
                </p>
            </div>

            {/* Profile Section */}
            <div style={styles.profileBox}>
                <div style={{ ...styles.profileCol, borderRight: '1px solid #e9d5ff' }}>
                    <h3 style={styles.profileName}>{bride.name}</h3>
                    <p style={styles.label}>{t('kundaliMatch.bride', 'Bride')}</p>
                </div>
                <div style={styles.profileCol}>
                    <h3 style={styles.profileName}>{groom.name}</h3>
                    <p style={styles.label}>{t('kundaliMatch.groom', 'Groom')}</p>
                </div>
            </div>

            {/* Main Score */}
            <div style={styles.scoreContainer}>
                <div style={styles.scoreCircle}>
                    <span style={{ fontSize: '32px', fontWeight: 'bold', color: matchResult.total_score >= 18 ? '#16a34a' : '#dc2626' }}>
                        {matchResult.total_score}
                    </span>
                    <span style={styles.scoreTotal}>/36</span>
                </div>
                <h2 style={{ fontSize: '20px', fontWeight: '600', margin: '8px 0', color: '#1f2937' }}>
                    {t('kundaliMatch.overallScore', 'Overall Compatibility Score')}
                </h2>
                <p style={{ color: '#4b5563', maxWidth: '500px', margin: '0 auto', fontSize: '14px' }}>
                    {matchResult.summary}
                </p>
            </div>

            {/* Ashta Koota Table */}
            <div style={{ marginBottom: '30px' }}>
                <h3 style={styles.sectionTitle}>
                    {t('kundaliMatch.ashtaKoota', 'Ashta Koota Breakdown')}
                </h3>
                <table style={styles.table}>
                    <thead>
                        <tr>
                            <th style={styles.th}>{t('kundaliMatch.area', 'Area')}</th>
                            <th style={styles.thCenter}>{t('kundaliMatch.points', 'Points')}</th>
                            <th style={styles.th}>{t('kundaliMatch.description', 'Description')}</th>
                        </tr>
                    </thead>
                    <tbody>
                        {matchResult.koota_details?.map((k, i) => (
                            <tr key={i} style={i % 2 !== 0 ? styles.rowAlt : {}}>
                                <td style={{ ...styles.td, fontWeight: '500' }}>{k.name}</td>
                                <td style={styles.tdPoints}>{k.points}/{k.max_points}</td>
                                <td style={styles.td}>{k.significance}</td>
                            </tr>
                        ))}
                    </tbody>
                </table>
            </div>

            {/* Manglik & Dosha */}
            <div style={styles.analysisContainer}>
                <div style={styles.manglikBox}>
                    <h4 style={styles.redTitle}>{t('kundaliMatch.manglikAnalysis', 'Manglik Analysis')}</h4>
                    <p style={styles.ptext}>
                        <strong>{t('kundaliMatch.bride', 'Bride')}:</strong> {matchResult.bride?.manglik_status}
                    </p>
                    <p style={styles.ptext}>
                        <strong>{t('kundaliMatch.groom', 'Groom')}:</strong> {matchResult.groom?.manglik_status}
                    </p>
                </div>
                <div style={styles.doshaBox}>
                    <h4 style={styles.orangeTitle}>{t('kundaliMatch.doshaAnalysis', 'Dosha Analysis')}</h4>
                    <ul style={{ margin: '0', paddingLeft: '20px', fontSize: '14px', color: '#374151' }}>
                        {matchResult.doshas?.filter(d => d.is_present).map((d, i) => (
                            <li key={i} style={{ marginBottom: '4px' }}>{d.name}</li>
                        ))}
                        {!matchResult.doshas?.some(d => d.is_present) && (
                            <li style={{ fontStyle: 'italic', color: '#6b7280', listStyle: 'none' }}>
                                {t('kundaliMatch.noMajorDoshas', 'No major doshas found')}
                            </li>
                        )}
                    </ul>
                </div>
            </div>

            {/* AI Analysis */}
            <div style={{ marginBottom: '30px' }}>
                <h3 style={styles.sectionTitle}>
                    {t('kundaliMatch.expertAnalysis', 'Astrological Expert Analysis')}
                </h3>
                <div style={styles.aiBox}>
                    {matchResult.ai_analysis}
                </div>
            </div>

            {/* Footer */}
            <div style={styles.footer}>
                <p>© {new Date().getFullYear()} AstroPinch. {t('common.allRightsReserved', 'All Rights Reserved')}.</p>
            </div>
        </div>
    );
});

export default MatchReportPDF;
